export const PromotionApi = [
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },
    {
        promHead : "BRAND PROMOTION",
promBox1 : "",
promBox2 : "Biw Biw India",
promBox3 : "Biw Biw crafts luxury facial products at affordable prices, this is one of our best campaigns which gained unpredictable ROI, A reel from this campaign went viral and marked wonderful sales.",
promNum1 : "6",
promNum2 : "900K+",
promBoxImg : "",
    },

]